# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bdrba\Documents\QTDesign\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
        #! WARNING: Any manual changes made to this file will be lost when pyuic5 is
        #! run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np



BOTTONE_MATRICE_STANDARD = (
                "QPushButton {\n"
                " padding: 0;\n"
                " border: none;\n"
                " display:inline-block;\n"
                " margin-left:0;\n"
                " margin-right:0;\n"
                "    background-color: white;\n"
                "}\n"
                "QPushButton:hover {\n"
                "    background-color: gray;\n"
                "}\n"
                "QPushButton:pressed {\n"
                "    background-color: black;\n"
                "}\n")

BOTTONE_MATRICE_CLICCATO = (
                "QPushButton {\n"
                " padding: 0;\n"
                " border: none;\n"
                " display:inline-block;\n"
                " margin-left:0;\n"
                " margin-right:0;\n"
                "    background-color: black;\n"
                "}\n"
                "QPushButton:hover {\n"
                "    background-color: gray;\n"
                "}\n"
                "QPushButton:pressed {\n"
                "    background-color: black;\n"
                "}\n"
            )

class Ui_MainWindow(object):
    clickedMatrix = [];

    def buttonClicked(self, i, j,button):
        if([i,j] in self.clickedMatrix):
            button.setStyleSheet(BOTTONE_MATRICE_STANDARD)
            self.clickedMatrix.remove([i,j])
            print("lo rimuovo dalla matrice")
        else:
            self.clickedMatrix.append([i,j])
            button.setStyleSheet(BOTTONE_MATRICE_CLICCATO)
            print("lo aggiungo alla matrice")
        print(self.clickedMatrix)
        
    def buttonsGenerator(self, m, n):
        #matrix_buttons = [];
        for i in range(m):
            for j in range(n):
                pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(pushButton_4.sizePolicy().hasHeightForWidth())
                pushButton_4.setSizePolicy(sizePolicy)

                palette = QtGui.QPalette()
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
                brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
                brush.setStyle(QtCore.Qt.SolidPattern)
                palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)

                pushButton_4.setPalette(palette)
                pushButton_4.setStyleSheet(BOTTONE_MATRICE_STANDARD)


                pushButton_4.setObjectName("button_{}".format(str(i)+str(j)))
                pushButton_4.clicked.connect(lambda ch, i=i,j=j,button=pushButton_4: self.buttonClicked(i,j,button))

                self.grid.addWidget(pushButton_4, i, j)


        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(15, 20, 15, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.patternNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.patternNameLineEdit.setStatusTip("")
        self.patternNameLineEdit.setWhatsThis("")
        self.patternNameLineEdit.setStyleSheet("QLineEdit{\n"
        "    color: #494949 !important;\n"
        "    text-decoration: none;\n"
        "    background: #ffffff;\n"
        "    margin-bottom:5px;\n"
        "    padding: 0.2em;\n"
        "    border: 4px solid #494949 !important;\n"
        "}")
        self.patternNameLineEdit.setInputMask("")
        self.patternNameLineEdit.setText("")
        self.patternNameLineEdit.setObjectName("patternNameLineEdit")
        self.horizontalLayout_2.addWidget(self.patternNameLineEdit)
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setStyleSheet("QPushButton {\n"
        "    color: #494949 !important;\n"
        "    text-transform: uppercase;\n"
        "    text-decoration: none;\n"
        "    background: #ffffff;\n"
        "    margin-bottom:5px;\n"
        "    padding: 0.2em;\n"
        "    border: 4px solid #494949 !important;\n"
        "    transition: all 0.4s ease 0s;\n"
        "    border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    color: #ffffff !important;\n"
        "    background: #f6b93b;\n"
        "    border-color: #f6b93b !important;\n"
        "    transition: all 0.4s ease 0s;\n"
        "}")
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout_2.addWidget(self.settingsButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grid = QtWidgets.QGridLayout()
        self.grid.setContentsMargins(15, -1, -1, -1)
        self.grid.setSpacing(0)
        self.grid.setObjectName("grid")

        ##########################
        self.buttonsGenerator(4,8)
        # ##########################
        
        self.horizontalLayout.addLayout(self.grid)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.insertButton = QtWidgets.QPushButton(self.centralwidget)
        self.insertButton.setStyleSheet("QPushButton {\n"
        "    color: #494949 !important;\n"
        "    text-transform: uppercase;\n"
        "    text-decoration: none;\n"
        "    background: #ffffff;\n"
        "    margin-bottom:5px;\n"
        "    padding: 0.2em;\n"
        "    border: 4px solid #494949 !important;\n"
        "    transition: all 0.4s ease 0s;\n"
        "    border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    color: #ffffff !important;\n"
        "    background: #f6b93b;\n"
        "    border-color: #f6b93b !important;\n"
        "    transition: all 0.4s ease 0s;\n"
        "}")
        self.insertButton.setObjectName("insertButton")
        self.verticalLayout_2.addWidget(self.insertButton)
        self.searchPatternButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchPatternButton.setStyleSheet("QPushButton {\n"
        "    color: #494949 !important;\n"
        "    text-transform: uppercase;\n"
        "    text-decoration: none;\n"
        "    background: #ffffff;\n"
        "    margin-bottom:5px;\n"
        "    padding: 0.2em;\n"
        "    border: 4px solid #494949 !important;\n"
        "    transition: all 0.4s ease 0s;\n"
        "    border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    color: #ffffff !important;\n"
        "    background: #f6b93b;\n"
        "    border-color: #f6b93b !important;\n"
        "    transition: all 0.4s ease 0s;\n"
        "}")
        self.searchPatternButton.setObjectName("searchPatternButton")
        self.verticalLayout_2.addWidget(self.searchPatternButton)
        self.searchSizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchSizeButton.setStyleSheet("QPushButton {\n"
        "    color: #494949 !important;\n"
        "    text-transform: uppercase;\n"
        "    text-decoration: none;\n"
        "    background: #ffffff;\n"
        "    margin-bottom:5px;\n"
        "    padding: 0.2em;\n"
        "    border: 4px solid #494949 !important;\n"
        "    transition: all 0.4s ease 0s;\n"
        "    border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    color: #ffffff !important;\n"
        "    background: #f6b93b;\n"
        "    border-color: #f6b93b !important;\n"
        "    transition: all 0.4s ease 0s;\n"
        "}")
        self.searchSizeButton.setObjectName("searchSizeButton")
        self.verticalLayout_2.addWidget(self.searchSizeButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "App"))
        self.patternNameLineEdit.setToolTip(_translate("MainWindow", "Pattern name to look for/save"))
        self.patternNameLineEdit.setPlaceholderText(_translate("MainWindow", "Pattern name"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.insertButton.setText(_translate("MainWindow", "Insert"))
        self.searchPatternButton.setText(_translate("MainWindow", "Search pattern"))
        self.searchSizeButton.setText(_translate("MainWindow", "Search size"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
